---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy
spec:
  selector:
    matchLabels:
      app: python-deploy
  template:
    metadata:
      labels:
        app: python-deploy
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: python-deploy
        image: python-deployment
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
